### ISSUE TITLE
Which World Bank data package?

### ISSUE THREAD

**Issue by briatte** [briatte/dsr#21]
https://vincentarelbundock.github.io/WDI/ by @vincentarelbundock (current choice)
https://github.com/gshs-ornl/wbstats by @jpiburn (more dependencies)
https://github.com/jpiburn/wbdata also by @jpiburn (unreleased?)

Does one of them also allow to download WB shapefiles?

**Comment by vincentarelbundock** [comment]
No shapefiles in `WDI`, unfortunately.

**Comment by briatte** [comment]
@vincentarelbundock Thanks. I'm not even sure I want to stick with WB shapefiles -- they don't seem to react well to `st_transform`.

**Comment by briatte** [comment]
Keeping `WDI` for now because of the `latest` argument (not in the online docs, but definitely there), which is handy to get the most recent nonmissing value of an indicator.

(`wbstats` has more dependencies but all of them are tidyverse, so that's not an issue.)

**Comment by briatte** [comment]
Sticking with `WDI` unless @gshs-ornl adds extra features that might come in handy.
