### ISSUE TITLE
Website does not exist?

### ISSUE THREAD

**Issue by Leschonander** [briatte/dsr#7]
Hello their,

I tried running this code to pull the most recenct CPJ data into, R, but the link seemingly does not work and I can't find the CPJ database that goes up to 2017 in Excel. Would you happen to possess that dataset to update the link and/or code?

```
u = "https://www.cpj.org/killed/cpj-database.xls"
f = basename(u) # New_York_Times_Brexit_coverage.xlsx

if (!file.exists(f))
  download.file(u, f, mode = "wb")
```

Thanks for taking the time to look at this pull-request.

**Comment by briatte** [comment]
Hi @Leschonander 

All apologies for answering this very, very late.

The CPJ has redesigned its website, and you will now need to use links the one below to access their data.

https://cpj.org/data/imprisoned/2017/?status=Imprisoned&start_year=2017&end_year=2017&group_by=location

This, of course, breaks [the code](https://github.com/briatte/dsr/blob/master/s2/cpj-journalists.r) that relied on the former URL. However, given that I ended not teaching the course that I started in this repository, I am unlikely to fix the issue at any point. Sorry… !
